import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.scss";
import { isMobileUserAgent } from '@/utils/isMobileUserAgent/isMobileUserAgent';
import { headers } from 'next/headers';
import NavBarDesktop from './components/NavBarDesktop'
import NavBarMobile from "./components/NavBarMobile";

const inter = Inter({
  weight: ["100", "300", "600", "900"],
  style: ["normal", "italic"],
  subsets: ["latin"]
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  let isMobile = null;

  async function getViewPort() {
    const headersList = await headers();
    const userAgent = headersList.get('user-agent') || '';
    isMobile = isMobileUserAgent(userAgent);
  }

  getViewPort()

  return (
    <html lang="pt-br">
      <body className={`${inter.className}`}>
        {!isMobile && <NavBarDesktop />}
        {children}
        {isMobile && <NavBarMobile />}
      </body>
    </html>
  );
}
